### ISSUE TITLE
Setting up varnomen.hgvs.org CNAME

### ISSUE THREAD

**Issue by martijnvermaat** [HGVSnomenclature/VarNomen#20]
Hi @williamOP @ifokkema @jtdendunnen :hand: 

Today I had a chat with Johan about the hosting of this site.

I saw that the `CNAME` file in the root of this repository currently contains `HGVS.org/varnomen`:

https://github.com/HGVSnomenclature/VarNomen/blob/master/CNAME

However, that is not a valid domain name, since the domain name cannot include a path. We decided it would be easiest to host the new nomenclature at `varnomen.hgvs.org`, which is a valid domain name.

This needs the following actions:
1. Change the `CNAME` file in this repository to contain `varnomen.hgvs.org`. This is for @williamOP :sunglasses:
2. Update the `hgvs.org` DNS records to [include a CNAME record pointing to GitHub Pages](https://help.github.com/articles/setting-up-a-custom-subdomain/). This is for @ifokkema :bowtie:

According to the GitHub docs it is best to execute these steps in this order.

See the [documentation on using a custom domain](https://help.github.com/articles/using-a-custom-domain-with-github-pages/) for more information or feel free to ask me if something isn't clear or doesn't work.

@ifokkema This setup does not need access to the HGVS webserver via FTP or otherwise.

Cheers!

**Comment by williamOP** [comment]
> Change the CNAME file in this repository to contain varnomen.hgvs.org. This is for @williamOP :sunglasses:

Done

**Comment by ifokkema** [comment]
> Update the hgvs.org DNS records to include a CNAME record pointing to GitHub Pages. This is for @ifokkema :bowtie: 

Hmm... I could look up who owns that domain name, if that is what you mean by assigning this to me :confused: I'll see what I can do... :sunglasses:

**Comment by martijnvermaat** [comment]
@ifokkema Sorry, I assumed you were in control of the domain name...

**Comment by ifokkema** [comment]
No, it's registered elsewhere. I just whois'ed it, and emailed the email address associated with it. I obviously did have email contact before with this person, so it's not a stranger to me ;) We'll see if it's possible to get done soon!

**Comment by ifokkema** [comment]
OK, my mail got forwarded to the right person, and he added the CNAME record. Links to stylesheets are not correct though, and the site looks malformed because of that:
http://varnomen.hgvs.org/
That would be up to @williamOP  to fix then :wink:

**Comment by williamOP** [comment]
Styling is fixed for http://varnomen.hgvs.org/ but it breaks the styling for http://hgvsnomenclature.github.io/VarNomen/ although that shouldn't be a problem.

**Comment by martijnvermaat** [comment]
That shouldn't be a problem indeed.

It looks great, thanks to you both!
