### ISSUE TITLE
Clarify whether `m.1000_100del` is allowed or not.

### ISSUE THREAD

**Issue by ifokkema** [HGVSnomenclature/VarNomen#33]
For circular genomes, like the mitochondrial genome, it is suggested that specifying ranges like `m.1000_100` is allowed. These ranges should then be interpreted as "1000 to end of reference sequence" and "start of reference sequence to 100", combined.

The HGVS website is super vague about whether or not this is valid HGVS.
One [source](http://varnomen.hgvs.org/recommendations/DNA/variant/deletion/) describes that this is allowed; it states;
> the “position(s)_deleted” should be listed from 5’ to 3’, e.g. 123_126 not 126_123.
> **exception**
> when a circular genomic reference sequnce is used (“o.” and “m.” prefix) nucleotide positions may be listed from 3’ to 5’ when the deletion includes both the last and first nucleotides of the reference sequence

Another [source](http://varnomen.hgvs.org/recommendations/open-issues/#circular), however, disputes this;
> July 19 (2016) - (...) How should one describe a variant involving the “first” and “last” nucleotides of the circular molecule? For now the suggestion is to describe the variant as m.[1del;16569del]. The question is whether m.16569_1del should be allowed (NOTE: includes an exception to the rule that in Y_Xdel X should be smaller then Y). Do you have a suggestion??

If indeed `m.1000_100del` is HGVS syntax, then this should be clarified.

Related:
https://github.com/openvar/variantValidator/issues/351

**Comment by jtdendunnen** [comment]
You are right, thanks for pointing this out!  When the exception for circular reference sequences (m. and o.) was accepted, we neglected to move the Open Issue to the Closed Issue section. We have now corrected this.
